Repository clubcompass/clubcompass.net, pull requests merged in 2021-12, with the labels that each got.

#24 🪄 Fix Spacing on Card Component (#11)
  components/cards/Card.jsx
  components/cards/CardContainer.jsx
  components/tags/Tag.jsx
Labels: 💧 client, 🪄 razzmatazz

#25 💧✨ Authentication with Supabase (#17)
  .gitignore
  components/tags/Tag.jsx
  config/supabase.js
  context/auth.js
  context/index.js
  package-lock.json
  package.json
  pages/_app.js
  pages/dashboard.jsx
  pages/index.jsx
  pages/login.jsx
  pages/signup.jsx
Labels: :sparkles: feature, 💧 client

#29 💧🪄 Truncate Long Descriptions (#23)
  components/cards/Card.jsx
  components/cards/Cards.jsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: 💧 client, 🪄 razzmatazz

#35 💧🪄 Validation and styling for auth (#26)
  components/auth/Field.jsx
  components/auth/FieldError.jsx
  components/auth/FormButton.jsx
  components/auth/FormWrapper.jsx
  components/auth/Graphic.jsx
  components/auth/index.js
  package-lock.json
  package.json
  pages/login.jsx
  pages/register.jsx
  pages/signup.jsx
  public/cc-auth.svg
  public/cc.svg
  tailwind.config.js
Labels: 💧 client, 🪄 razzmatazz

#37 💧🪄 Mobile login and register page tweaks (#36)
  components/cards/Card.jsx
  package-lock.json
  package.json
  pages/login.jsx
  pages/register.jsx
Labels: 💧 client, 🪄 razzmatazz

#47 💧✨ Club Page (#42)
  components/cards/Card.jsx
  components/icons/Icons.jsx
  components/icons/index.js
  package-lock.json
  package.json
  pages/club/[name].jsx
Labels: :sparkles: feature, 💧 client

#54 ✨ Update Club Information (#53)
  pages/api/update/club/description.js
  pages/api/update/club/email.js
  pages/api/update/club/image_caption.js
  pages/api/update/club/image_link.js
  pages/api/update/club/link.js
  pages/api/update/club/link_name.js
  pages/api/update/club/meeting_location.js
  pages/api/update/club/meeting_time.js
  pages/api/update/club/name.js
  pages/api/update/club/president.js
  pages/api/update/club/tags.js
  pages/api/update/club/teacher.js
Labels: :sparkles: feature, :cloud: backend

#60 🛠 Tidy general layout (#59)
  components/clubs/Card.jsx
  components/clubs/CardContainer.jsx
  components/clubs/index.js
  components/layout/Footer.jsx
  components/layout/Layout.jsx
  components/layout/Navigation.jsx
  components/layout/index.js
  next.config.js
  pages/_app.js
  pages/club/[name].jsx
  pages/clubs.jsx
  pages/clubs/[slug].jsx
  pages/index.jsx
  pages/login.jsx
  pages/register.jsx
  tailwind.config.js
Labels: 💧 client, 🛠 refactoring

#63 🪄 Fix Route and Naming for Club Pages (#62)
  components/clubs/Card.jsx
  package-lock.json
  pages/club/[name].jsx
Labels: :bug: bug, 💧 client

#67 🛠 Update all existing update methods (#66)
  lib/db/create.js
  lib/db/delete.js
  lib/db/get.js
  lib/db/update.js
Labels: :bug: bug, 💧 client, 🛠 refactoring

#72 ✨ Create ToolTip Component
  components/general/ToolTip.jsx
Labels: :sparkles: feature, 💧 client

#73 ✨ Create CopyText Component
  components/general/CopyText.jsx
Labels: :sparkles: feature, 💧 client

#78 🪄 Added support for slugs in schema (#77)
  pages/api/create/club.js
  pages/api/get/clubBySlug.js
  prisma/schema.prisma
Labels: :cloud: backend, 🪄 razzmatazz

#86 🚑 Added filtering by multiple tags (#85)
  pages/api/get/club.js
  pages/api/get/clubBySlug.js
Labels: :cloud: backend, 🚑 critical hot-fix

#90 🏥 Fixed getting clubs by tag (#89)
  package-lock.json
  package.json
  pages/api/get/club.js
Labels: :cloud: backend, 🏥 Repairs

#94 🛠 Basic data integration on client (#74)
  components/clubs/Card.jsx
  components/icons/Icons.jsx
  components/tags/Tag.jsx
  components/tags/Tags.jsx
  components/tags/tagsSchema.js
  lib/db/get.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/get/tags.js
  pages/club/[name].jsx
  pages/clubs.jsx
  tailwind.config.js
Labels: 💧 client, 🪄 razzmatazz, 🛠 refactoring
