Repository clubcompass/clubcompass.net, pull requests merged in 2022-01, with the labels that each got.

#124 🪄 Set all card heights to 223px (#120)
  components/clubs/Card.jsx
Labels: 💧 client, 🪄 razzmatazz

#95 🚨 Seeding database script (#68)
  package.json
  seed_script/clubs.json
  seed_script/seed.js
  seed_script/users.json
Labels: :cloud: backend, 🚨 testing

#140 ⚡ Added support for caching (#138)
  config/redis.js
  package-lock.json
  package.json
  pages/api/create/cache.js
  pages/api/get/club.js
Labels: :sparkles: feature, :cloud: backend, ⚡️ performance

#141 📄 404 Page (#97)
  pages/404.jsx
  public/cc-404.svg
Labels: 💧 client, 📄 page

#148 🛠 Refactor client side (#118)
  components/clubs/Card.jsx
  components/clubs/index.js
  components/general/Button.jsx
  components/general/Link.jsx
  components/general/icons/Icons.jsx
  components/general/icons/index.js
  components/general/tags/PrimaryTag.jsx
  components/general/tags/Tag.jsx
  components/general/tags/Tags.jsx
  components/general/tags/index.js
  components/general/tags/tagsSchema.js
  components/layout/footer/Footer.jsx
  components/layout/index.js
  components/layout/navigation/Navigation.jsx
  components/pages/auth/Field.jsx
  components/pages/auth/FieldError.jsx
  components/pages/auth/FormButton.jsx
  components/pages/auth/FormWrapper.jsx
  components/pages/auth/Graphic.jsx
  components/pages/auth/index.js
  components/pages/clubs/Card.jsx
  components/pages/clubs/CardContainer.jsx
  components/pages/clubs/CardContent.jsx
  components/pages/clubs/CardFooter.jsx
  components/pages/clubs/CardHeader.jsx
  components/pages/clubs/Clubs.jsx
  components/pages/clubs/ClubsWrapper.jsx
  components/pages/clubs/index.js
  lib/db/create.js
  lib/db/delete.js
  lib/db/update.js
  pages/clubs.jsx
  pages/login.jsx
  pages/register.jsx
Labels: 💧 client, 🛠 refactoring

#149 🔒 Middleware and env vars to secure api (#88)
  pages/api/_middleware.js
Labels: :sparkles: feature, :cloud: backend, ⚡️ performance, 🔒 security

#166 🛠 Prepare and purge register page (#159)
  .gitignore
  components/general/input/Field.jsx
  components/general/input/OptionSelection.jsx
  components/general/input/TagSelection.jsx
  components/pages/register/RegisterPagination.jsx
  components/pages/register/onboarding/components/OnboardingButton.jsx
  components/pages/register/onboarding/components/OnboardingHeader.jsx
  components/pages/register/onboarding/components/OnboardingWrapper.jsx
  components/pages/register/onboarding/slides/ClosingSlide.jsx
  components/pages/register/onboarding/slides/EmailSlide.jsx
  components/pages/register/onboarding/slides/InformationSlide.jsx
  components/pages/register/onboarding/slides/InterestsSlide.jsx
  components/pages/register/onboarding/slides/IntroSlide.jsx
  components/pages/register/onboarding/slides/PasswordSlide.jsx
  package-lock.json
  pages/register.jsx
Labels: 💧 client, 🛠 refactoring

#193 🛠 Update user schema add grades+interests (#192)
  pages/api/create/user.js
  pages/api/get/user.js
  prisma/schema.prisma
  seed_script/seed.js
  seed_script/users.json
Labels: :cloud: backend, 🛠 refactoring

#216 🧩 `Nav` component (#160)
  components/custom/cc.jsx
  components/custom/index.js
  components/general/tags/Tag.jsx
  components/layout/Layout.jsx
  components/layout/index.js
  components/layout/navigation/Nav.jsx
  components/layout/navigation/NavHamburger.jsx
  components/layout/navigation/NavItems.jsx
  components/layout/navigation/NavLink.jsx
  components/layout/navigation/NavLogin.jsx
  components/layout/navigation/NavLogo.jsx
  components/layout/navigation/NavMenu.jsx
  components/layout/navigation/NavProfile.jsx
  components/layout/navigation/Navigation.jsx
  components/layout/navigation/index.js
  context/index.js
  context/layout.js
  hooks/index.js
  hooks/useBreakpoints.js
  hooks/useMediaQuery.js
  package-lock.json
  public/cc-auth.svg
  tailwind.config.js
Labels: 💧 client, 🧩 component
