Repository clubcompass/clubcompass.net, pull requests merged in 2022-02, with the labels that each got.

#208 📄 Auth: `Register` Page (#157)
  components/general/input/Field.jsx
  components/general/input/OptionSelection.jsx
  components/general/input/TagSelection.jsx
  components/general/input/control/Field.jsx
  components/general/input/control/FieldButton.jsx
  components/general/input/control/FormControl.jsx
  components/general/input/control/index.js
  components/general/input/index.js
  components/pages/register/RegisterContainer.jsx
  components/pages/register/RegisterPagination.jsx
  components/pages/register/index.js
  components/pages/register/onboarding/components/OnboardingButton.jsx
  components/pages/register/onboarding/components/OnboardingButtons.jsx
  components/pages/register/onboarding/components/OnboardingContainer.jsx
  components/pages/register/onboarding/components/OnboardingHeader.jsx
  components/pages/register/onboarding/components/OnboardingWrapper.jsx
  components/pages/register/onboarding/components/index.js
  components/pages/register/onboarding/components/input/OnboardingField.jsx
  components/pages/register/onboarding/components/input/OnboardingFieldButton.jsx
  components/pages/register/onboarding/components/input/OnboardingForm.jsx
  components/pages/register/onboarding/slides/ClosingSlide.jsx
  components/pages/register/onboarding/slides/EmailSlide.jsx
  components/pages/register/onboarding/slides/InformationSlide.jsx
  components/pages/register/onboarding/slides/InterestsSlide.jsx
  components/pages/register/onboarding/slides/IntroSlide.jsx
  components/pages/register/onboarding/slides/PasswordSlide.jsx
  components/pages/register/onboarding/slides/SummarySlide.jsx
  components/pages/register/onboarding/slides/index.js
  lib/auth/authorize.js
  lib/auth/index.js
  lib/auth/login.js
  lib/auth/logout.js
  lib/auth/register.js
  package-lock.json
  package.json
  pages/api/auth/authorize.js
  pages/api/auth/login.js
  pages/api/auth/logout.js
  pages/api/auth/mail.js
  pages/api/auth/register.js
  pages/dashboard.jsx
  pages/login.jsx
  pages/register.jsx
  utils/setCookie.js
  utils/validation/index.js
  utils/validation/schemas/index.js
  utils/validation/schemas/newUserSchema.js
  utils/validation/schemas/userSchema.js
  utils/validation/validate.js
Labels: 💧 client, 🛠 refactoring, 📄 page

#222 🏥 Register page cleanup (#209)
  components/general/input/TagSelection.jsx
  components/pages/register/onboarding/components/input/OnboardingForm.jsx
  components/pages/register/onboarding/slides/SummarySlide.jsx
  pages/api/auth/mail.js
Labels: 💧 client, 🪄 razzmatazz, 🏥 repairs

#230 ✨ Link support (#229)
  lib/db/club.js
  pages/api/club/links/add.js
  pages/api/club/links/get.js
  pages/api/club/links/remove.js
Labels: :sparkles: feature, :cloud: backend

#239 🌱 Seed script rewrite (#233)
  seed_script/clubs.json
  seed_script/seed.js
Labels: :cloud: backend, 🌱 seed

#238 ✨ Added support for invites (#237)
  lib/database.js
  lib/db/index.js
  lib/db/invite.js
  pages/api/club/get.js
  pages/api/invite/accept.js
  pages/api/invite/create.js
  pages/api/invite/decline.js
  pages/api/invite/delete.js
  pages/api/user/get.js
  prisma/schema.prisma
Labels: :sparkles: feature, :cloud: backend

#241 ✨ Support for club availability (#240)
  lib/db/club.js
  pages/api/club/update/availability.js
  prisma/schema.prisma
Labels: :sparkles: feature, :cloud: backend

#246 🔀 Master -> loading-height-245
  components/general/Loading.jsx
Labels: :bug: bug, 💧 client

#250 ✨ Added support for role descriptions (#249)
  lib/db/role.js
  pages/api/role/create.js
  prisma/schema.prisma
Labels: :sparkles: feature, :cloud: backend

#248 ✨ Support for club compass id (#247)
  lib/db/user.js
  pages/api/user/create.js
  pages/api/user/get.js
  prisma/schema.prisma
Labels: :sparkles: feature, :cloud: backend

#243 ✨ Support for club finances (#242)
  pages/api/club/create.js
  pages/api/club/get.js
  prisma/schema.prisma
Labels: :sparkles: feature, :cloud: backend

#244 🔀 Master -> club-page-ui-rework-223
  components/general/CopyText.jsx
  components/general/ToolTip.jsx
  components/general/tags/Tags.jsx
  components/pages/club/Club.jsx
  components/pages/club/ClubCarousel.jsx
  components/pages/club/ClubContact.jsx
  components/pages/club/ClubContent.jsx
  components/pages/club/ClubHeader.jsx
  components/pages/club/ClubMeeting.jsx
  components/pages/club/ClubMembers.jsx
  components/pages/club/ClubSimilarClubs.jsx
  components/pages/club/ClubWrapper.jsx
  components/pages/club/index.js
  package-lock.json
  package.json
  pages/club/[slug].jsx
  pages/clubs.jsx
Labels: 💧 client, 🎨 ui
